In [1]:
from finvizfinance.quote import finvizfinance
import pandas as pd

In [2]:
from finvizfinance.screener.overview import Overview

foverview = Overview()
filters_dict = {'Index':'Any','Sector':'Any'}
foverview.set_filter(filters_dict=filters_dict)
df = foverview.screener_view().copy()

In [3]:
df

,Ticker,Company,Sector,Industry,Country,Market Cap,P/E,Price,Change,Volume
0,A,"Agilent Technologies, Inc.",Healthcare,Diagnostics & Research,USA,3.856000e+10,30.98,127.63,-0.0067,1308095.0
1,AA,Alcoa Corporation,Basic Materials,Aluminum,USA,1.177000e+10,16.52,64.02,0.0354,5359512.0
2,AAAU,Goldman Sachs Physical Gold ETF,Financial,Exchange Traded Fund,USA,NaN,NaN,18.30,-0.0044,837683.0
3,AAC,Ares Acquisition Corporation,Financial,Shell Companies,USA,1.230000e+09,98.1,9.82,0.0010,1049212.0
4,AACG,ATA Creativity Global,Consumer Defensive,Education & Training Services,China,3.250000e+07,None,1.03,0.0145,1826.0
...,...,...,...,...,...,...,...,...,...,...
8585,ZWS,Zurn Water Solutions Corporation,Industrials,Pollution & Treatment Controls,USA,3.920000e+09,56.46,30.55,-0.0126,775125.0
8586,ZY,Zymergen Inc.,Basic Materials,Specialty Chemicals,USA,1.733100e+08,None,1.60,0.0323,903764.0
8587,ZYME,Zymeworks Inc.,Healthcare,Biotechnology,Canada,3.900000e+08,None,6.88,-0.0310,1522574.0
8588,ZYNE,"Zynerba Pharmaceuticals, Inc.",Healthcare,Drug Manufacturers - Specialty & Generic,USA,4.230000e+07,None,0.92,0.0096,164362.0
8589,ZYXI,"Zynex, Inc.",Healthcare,Medical Devices,USA,2.791700e+08,14.63,7.15,0.0014,396733.0

In [12]:
Sectors = ['Consumer Cyclical']
# 'Healthcare','Consumer Cyclical','Financial','Communication Services','Energy','Industrials','Basic Materials','Real Estate','Consumer Defensive','Utilities']

class Calculator:
    def __init__(self)
     self.new_data = self.create_df()
    
    
    def calc(sectors):
        data = df[df.Sector == sectors]
    
        calc = data[['Market Cap']].sum()[0]
        empty = pd.DataFrame()
        collect= {sectors:[calc]}
        create = pd.DataFrame(collect)
        empty[sectors] = create[sectors]
        return empty

    
    
    

    
    

calc('Consumer Cyclical')    

calc('Communication Services')
    

    
# a = df[df.Sector == 'Healthcare'][['Market Cap']].sum()[0]

# collect = {'Healthcare':[a]}

# # empty = pd.DataFrame()

# b = pd.DataFrame(collect)



# b



 

# empty['tech'] = b['tech'] 

# empty

   Communication Services
0            6.475271e+12

In [137]:
Group_Sector_market = df[['Sector',]]

In [50]:
a = Group_Sector_market.drop_duplicates(subset=['Sector'])

In [63]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)

from finvizfinance.group.performance import Performance as OV

view = OV()

view.screener_view().sort_values(['Volume'],ascending=False)

,Name,Perf Week,Perf Month,Perf Quart,Perf Half,Perf Year,Perf YTD,Recom,Avg Volume,Rel Volume,Change,Volume
9,Technology,-1.23%,-0.02,-0.06,-0.22,-0.10,-0.25,2.01,1720000000.00,0.92,-0.00,1440000000.00
6,Healthcare,-3.06%,-0.01,-0.02,-0.07,-0.08,-0.13,2.07,1490000000.00,0.81,-0.00,1100000000.00
2,Consumer Cyclical,-0.17%,-0.03,-0.04,-0.23,-0.24,-0.26,2.20,1480000000.00,0.80,0.01,1080000000.00
5,Financial,-1.05%,0.01,-0.00,-0.06,-0.10,-0.09,2.26,1050000000.00,0.63,0.00,599480000.00
1,Communication Services,0.86%,-0.00,-0.07,-0.21,-0.22,-0.23,1.91,784030000.00,0.67,0.01,475370000.00
4,Energy,1.20%,0.09,0.14,0.48,0.46,0.45,2.22,883230000.00,0.59,0.00,472900000.00
7,Industrials,0.80%,0.00,-0.01,-0.08,-0.10,-0.11,2.26,681360000.00,0.74,0.00,459720000.00
0,Basic Materials,-0.07%,0.03,0.01,0.09,-0.03,0.02,2.26,602200000.00,0.64,0.00,349840000.00
8,Real Estate,-0.49%,-0.02,-0.04,-0.10,-0.18,-0.17,2.22,380910000.00,0.79,-0.00,273520000.00
3,Consumer Defensive,-1.42%,-0.04,-0.01,-0.00,-0.05,-0.07,2.28,380020000.00,0.66,-0.00,227690000.00
10,Utilities,-0.85%,0.04,0.04,0.10,0.11,0.03,2.37,167960000.00,0.67,0.00,102210000.00